version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile.test
      context: .
    container_name: store_management_app_test
    volumes:
      - .:/store_management_app_test
    ports:
      - "5000:5000"
    depends_on:
      - db_test

  db_test:
    image: postgres
    container_name: store_management_db_test
    environment:
      - POSTGRES_DB=store_management_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
  
volumes:
  database_postgres_test: